### PR TITLE
Fix for Scratch Orgs Not created with JWT Bearer Flow

### LINKED ISSUE #542: Error Creating Pool with JWT Bearer Flow
**Describe the bug**
In a CI environment, when running the `sfpowerkit:pool:create` command after authorizing with the JWT Bearer Flow, you will see an error: "Unable to provision scratch org  1 . Due to following Error: undefined refreshToken". This is due to the fact that the JWT flow does not provide a refresh token.

**To Reproduce**

1. sfdx auth:jwt:grant -i ${client_id} -f ${key_file} -u ${devhub_username}
2. sfdx sfpowerkit:pool:create -f config/pool-config.json -v ${devhub_username}

**Expected behavior**
The pool should be created, and scratch orgs created in the pool, without error.

**Desktop (please complete the following information):**

- OS: Linux
- Node Version: 14.17.1
- Version of sfpowerkit: 3.1.5

**Additional context**
It appears the problem is this line of code: https://github.com/Accenture/sfpowerkit/blob/main/src/utils/scratchOrgUtils.ts#L199

Maybe wrapping in a try catch to handle any errors would be best, instead of halting the process of scratch org creation. It's also worth noting that the SfdxAuthUrl will not work with the JWT flow, because no refresh token is provided - unless I am missing something.

There was a change in the sfdx cli that now validates the existence of the refresh token, which might not have been the case when originally developed: https://github.com/forcedotcom/sfdx-core/pull/396

### PR DESCRIPTION
**Pull request by azlam-abdulsalam**
Fix #542

Scratch Orgs created from a DevHub using JWT bearer token doesnt have authURL. This was not enforced 
in the previsous version of salesforce-core lib. 

This will allow pools to be created, but will show an info message.﻿

### CODE REVIEW

**Review by aly76 — APPROVED** [review]

File: src/utils/scratchOrgUtils.ts [hunk 1]
```diff
@@ -194,9 +194,18 @@ export default class ScratchOrgUtils {
...
+    try
+    {
     const authInfo = await AuthInfo.create({ username: scratchOrg.username });
-
     scratchOrg.sfdxAuthUrl = authInfo.getSfdxAuthUrl();
+    }
+    catch(error)
+    {
+      SFPowerkit.log(
+        `Unable to fetch authURL for ${passwordData.username}. Only Scratch Orgs created from DevHub using authenticated using auth:sfdxurl or auth:web will have access token and enabled for autoLogin`,
```
Comment (aly76) [inline src/utils/scratchOrgUtils.ts:205]: passwordData.username?
