### PR TITLE
Fix for Issue #625 sandbox refresh

### LINKED ISSUE #625: Sandbox description field is empty after sfpowerkit:org:sandbox:refresh
**Describe the bug**
Description field is empty on Sandboxes that the refresh process was initiated with sfpowerkit:org:sandbox:refresh.

**To Reproduce**
1. Issue the refresh via sfdx sfpowerkit plugin with `sfdx sfpowerkit:org:sandbox:refresh  --licensetype DEVELOPER --name dxpreprod --targetdevhubusername redacted.email.com`
2. After the refresh process is finished, check on your org: browse to setup > sanboxes, then check the list with all sandboxes.
Example 1: sandbox refresh via sfpowerkit plugin: The description (last) field is empty.

Example 2: sandbox that was refresh via Salesforce UI. The description (last) field is kept.

**Expected behavior**
Refresh initiated via sfpowerkit plugin should behave as the behavior on Salesforce UI.

**Screenshots**
Example 1: This sandbox was refreshed via sfpowerkit plugin: 
The description (last) field is empty.
image

Example 2: One sandbox that was refreshed via Salesforce UI. 
The description (last) field is kept.
image

**Desktop (please complete the following information):**

- OS: Linux
- sfpowerkit 4.0.3
- sfdx-cli/7.133.0 linux-x64 node-v16.13.1

### PR DESCRIPTION
**Pull request by Janani-26**
Fixes #625, Add description to sandbox refresh

### CODE REVIEW

**Comment by azlam-abdulsalam** [comment]
Thanks @Janani-26  for raising this, Would you be able to make the description an optional flag as well, so that it could be overridden from the command line

**Comment by Janani-26** [comment]
> Thanks @Janani-26 for raising this, Would you be able to make the description an optional flag as well, so that it could be overridden from the command line

@azlam-abdulsalam added the optional description flag

File: src/commands/sfpowerkit/org/sandbox/refresh.ts [hunk 1]
```diff
@@ -131,4 +174,19 @@ export default class Refresh extends SFPowerkitCommand {
 
     return sandbox_query_result.records[0].Id;
   }
+
+  public async getSandboxDescription(conn: Connection, name: string) {
+    const query_uri = `${conn.instanceUrl}/services/data/v${this.flags.apiversion}/tooling/query?q=SELECT+Description+FROM+SandboxInfo+WHERE+SandboxName+in+('${name}')`;
+
+    const sandbox_query_result = await request({
+      method: "get",
+      url: query_uri,
```
Comment (azlam-abdulsalam) [inline src/commands/sfpowerkit/org/sandbox/refresh.ts:183]: Thanks @Janani-26 , Would you be able to refactor this to use query executor?
https://github.com/Accenture/sfpowerkit/blob/main/src/utils/queryExecutor.ts

**Review by azlam-abdulsalam — CHANGES_REQUESTED** [review]
Request to use query executor

File: src/commands/sfpowerkit/org/sandbox/refresh.ts (hunk 1 above)
Comment (Janani-26) [reply src/commands/sfpowerkit/org/sandbox/refresh.ts]: @azlam-abdulsalam Refactored using Query Executor

Comment (Janani-26) [reply src/commands/sfpowerkit/org/sandbox/refresh.ts]: @azlam-abdulsalam - Could you please confirm if there are any other code refactoring has to be completed for this refresh command.

File: src/commands/sfpowerkit/org/sandbox/refresh.ts [hunk 2]
```diff
@@ -54,47 +62,81 @@ export default class Refresh extends SFPowerkitCommand {
...
+        result = await request({
+          method: "patch",
+          url: uri,
+          headers: {
+            Authorization: `Bearer ${conn.accessToken}`
+          },
+          body: {
+            AutoActivate: "true",
+            SourceId: `${sourceSandboxId}`,
+            Description: `${sandboxDescription}`
```
Comment (azlam-abdulsalam) [inline src/commands/sfpowerkit/org/sandbox/refresh.ts:98]: Can you reduce the duplication of the request by using conditional directly in the body? For eg:
```suggestion
            Description:this.flags.description?`${this.flags.description}`: `${sandboxDescription}`
```

File: src/commands/sfpowerkit/org/sandbox/refresh.ts [hunk 3]
```diff
@@ -54,47 +62,81 @@ export default class Refresh extends SFPowerkitCommand {
...
+      if (this.flags.description) {
+        result = await request({
+          method: "patch",
+          url: uri,
+          headers: {
+            Authorization: `Bearer ${conn.accessToken}`
+          },
+          body: {
+            AutoActivate: "true",
+            LicenseType: `${this.flags.licensetype}`,
```
Comment (azlam-abdulsalam) [inline src/commands/sfpowerkit/org/sandbox/refresh.ts:119]: This could Also move the construction of api request to a single function to eliminate duplicating code

**Review by azlam-abdulsalam — CHANGES_REQUESTED** [review]
@Janani-26 Please see my comments

File: src/commands/sfpowerkit/org/sandbox/refresh.ts [hunk 4]
```diff
@@ -31,6 +34,11 @@ export default class Refresh extends SFPowerkitCommand {
       char: "f",
       default: "",
       description: messages.getMessage("cloneFromFlagDescripton")
+    }), 
+    description: flags.string({
+      required: false,
+      char: "d",
+      description: messages.getMessage("descriptionFlagDescription")
```
Comment (manisfdcsfdx) [inline src/commands/sfpowerkit/org/sandbox/refresh.ts:41]: @Janani-26  flag description for descriptionFlagDescription should be added in [/messages/sandbox_refresh.json/messages/sandbox_refresh.json](https://github.com/Accenture/sfpowerkit/blob/main/messages/sandbox_refresh.json). 


Rest all looking good we will update the read me with new flags and help

Comment (manisfdcsfdx) [reply src/commands/sfpowerkit/org/sandbox/refresh.ts:41]: my bad flag description already exist. 

all good from my side.

**Review by manisfdcsfdx — APPROVED** [review]
Approved

**Review by azlam-abdulsalam — APPROVED** [review]
Thanks @Janani-26  for fixing this
