### PR TITLE
fix(valid): fix Package:valid to use source-deploy-retrieve library

### LINKED ISSUE #604: sfpowerkit:package:valid is unable to analyze packages
**Describe the bug**
sfpowerkit:package:valid is reporting 'Error Occured Unable to analyze <package>' on all packages

**To Reproduce**

1. sfdx sfpowerkit:package:valid -n <package>

**Expected behavior**

The command should execute properly and report contents that cant be placed in a unlocked package

**Screenshots**

**Desktop (please complete the following information):** 

- OS: [e.g. Windows/Linux] All
- Node Version: 14.X.X
- Version of sfpowerkit[e.g 1.45.0] 3.4.2 - Release December 21
- Salesforce Org Version [ In case of pre release window ]

**Additional context**

### PR DESCRIPTION
**Pull request by azlam-abdulsalam**
Package valid command is using sfdx node wrapper to convert to source format. The convert is
failing. Rather than fixing it, I have took the opportunity to use SDR to figure the component 
and filter based on it

fix #604

### CODE REVIEW

File: src/commands/sfpowerkit/package/valid.ts [hunk 1]
```diff
@@ -183,57 +181,31 @@ Elements supported included in your package testPackage
...
+      if (Array.isArray(components)) {
+        for (const component of components) {
             if (
-              this.coverageJSON.types[types["name"]].channels
+              this.coverageJSON.types[component.type.name].channels
                 .unlockedPackagingWithoutNamespace
             )
-              sfdx_package.supportedTypes.push(`${types["name"]}`);
-            else sfdx_package.unsupportedtypes.push(`${types["name"]}`);
+              sfdx_package.supportedTypes.push(`${COLOR_KEY_MESSAGE(component.type.name)}: ${component.name}   ${component.name}`);
```
Comment (aly76) [inline src/commands/sfpowerkit/package/valid.ts]: Duplicated `component.name`

**Review by aly76 — APPROVED** [review]
